gui:
  authorColors:
    'Pedro Pombeiro': '#11aaff'  # use a light blue for my commits
  branchColors:
    'pedropombeiro': '#11aaff'  # use a light blue for branches beginning with 'pedropombeiro/'
    '_pedropombeiro': '#808080'  # use gray for branches beginning with '_pedropombeiro/'
    'tmp': '#404040'  # use dark gray for branches beginning with 'tmp/'
  showIcons: true
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  language: auto
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
  showListFooter: true
  showFileTree: true
  showRandomTip: false
  showCommandLog: true
  commandLogSize: 8
git:
  paging:
    colorArg: always
    pager: |
      delta --dark --paging=never --no-gitconfig --24-bit-color=never
    useConfig: false
  commit:
    signOff: false
  merging:
    # only applicable to unix users
    manualCommit: false
    # extra args passed to `git merge`, e.g. --no-ff
    args: ""
  skipHookPrefix: WIP
  autoFetch: true
  branchLogCmd: |
    git log --graph --color=always --abbrev-commit --decorate --date=relative
            --pretty=medium {{branchName}} --
  allBranchesLogCmd: |
    git log --graph --all --color=always --abbrev-commit --decorate
            --date=relative --pretty=medium
  overrideGpg: true  # allows lazygit to spawn a separate process when using GPG
  disableForcePushing: false
  commitPrefixes: {}
  parseEmoji: false
  log:
    order: topo-order
    showGraph: when-maximised
  diffContextSize: 3
update:
  method: prompt
  days: 14
refresher:
  refreshInterval: 10  # file/submodule refresh interval in seconds
  fetchInterval: 60  # re-fetch interval in seconds
reporting: undetermined
splashUpdatesIndex: 0
confirmOnQuit: false
# determines whether hitting 'esc' will quit the application
# when there is nothing to cancel/close
quitOnTopLevelReturn: false
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ','
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: <
    gotoBottom: '>'
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    optionMenu: x
    optionMenu-alt1: '?'
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirm-alt1: "y"
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: <c-u>
    scrollDownMain-alt2: <c-d>
    executeCustomCommand: ':'
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: ']'
    prevTab: '['
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    appendNewline: <a-enter>
    extrasMenu: '@'
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: '`'
    openMergeTool: M
    openStatusFilter: <c-b>
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    viewGitFlowOptions: i
    fastForward: f
    pushTag: P
    setUpstream: u
    fetchRemote: f
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <c-j>
    moveUpCommit: <c-k>
    amendToCommit: A
    pickCommit: p
    revertCommit: t
    cherryPickCopy: c
    cherryPickCopyRange: C
    pasteCommits: v
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitMessageToClipboard: <c-y>
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
  stash:
    popStash: g
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleDragSelect: v
    toggleDragSelect-alt: V
    toggleSelectHunk: a
    pickBothHunks: b
  submodules:
    init: i
    update: u
    bulkMenu: b
os:
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}
disableStartupPopups: true
customCommands: []
services: {}
notARepository: prompt
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
